import CompaniesIcon from "../src/components/Layout/companines";
import Footer from "../src/components/Layout/Footer";
import Header from "../src/components/Layout/header";
import "rc-dropdown/assets/index.css";
import "../styles/globals.css";
import CartDrawerComponent from "../src/components/cart/CartDrawer";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
                <CartDrawerComponent />

                {children}
        <CompaniesIcon />
        <Footer />
      </body>
    </html>
  );
}
