import Footer from "../components/Layout/Footer";
import "../styles/globals.css";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        header
        {children}
        <Footer />
      </body>
    </html>
  );
}
