export const categories = [
  {
    name: "Living Room Furniture",
    subcategories: [
      "Sofas & Couches",
      "Sectionals",
      "Chairs",
      "Coffee & Accent Tables",
      "TV Stands & Entertainment Centers",
      "Bookshelves & Cabinets",
    ],
  },
  {
    name: "Bedroom Furniture",
    subcategories: [
      "Beds",
      "Dressers & Chests",
      "Nightstands",
      "Armoires & Wardrobes",
      "Vanities",
      "Bedroom Sets",
    ],
  },
  {
    name: "Dining Room Furniture",
    subcategories: [
      "Dining Tables",
      "Dining Chairs",
      "Buffets & Sideboards",
      "Bar & Counter Stools",
      "Dining Sets",
    ],
  },
  {
    name: "Home Office Furniture",
    subcategories: [
      "Desks",
      "Office Chairs",
      "Bookcases",
      "File Cabinets",
      "Office Sets",
    ],
  },
  {
    name: "Outdoor Furniture",
    subcategories: [
      "Patio Sets",
      "Outdoor Seating",
      "Outdoor Tables",
      "Outdoor Dining",
      "Outdoor Accessories",
    ],
  },
  {
    name: "Mattresses & Bedding",
    subcategories: [
      "Mattresses",
      "Bedding Sets",
      "Pillows",
      "Mattress Toppers",
      "Mattress Protectors",
    ],
  },
];

export const categoriess = [
  {
    name: "Living Room Furniture",
    subcategories: [
      "Sofas & Couches",
      "Sectionals",
      "Chairs",
      "Coffee & Accent Tables",
      "TV Stands & Entertainment Centers",
      "Bookshelves & Cabinets",
      "Rugs",
      "Lamps & Lighting",
      "Decorative Pillows",
      "Wall Art",
      "Curtains & Drapes",
      "Throw Blankets",
    ],
  },
  {
    name: "Bedroom Furniture",
    subcategories: [
      "Beds",
      "Dressers & Chests",
      "Nightstands",
      "Armoires & Wardrobes",
      "Vanities",
      "Bedroom Sets",
      "Mattresses",
      "Bedding",
      "Pillows",
      "Blankets & Throws",
      "Lamps & Lighting",
      "Wall Art",
      "Rugs",
    ],
  },
  {
    name: "Dining Room Furniture",
    subcategories: [
      "Dining Tables",
      "Dining Chairs",
      "Buffets & Sideboards",
      "Bar & Counter Stools",
      "Dining Sets",
      "Tablecloths & Runners",
      "Placemats & Napkins",
      "Dinnerware",
      "Drinkware",
      "Serveware",
      "Candles & Candle Holders",
      "Centerpieces",
    ],
  },
  {
    name: "Home Office Furniture",
    subcategories: [
      "Desks",
      "Office Chairs",
      "Bookcases",
      "File Cabinets",
      "Office Sets",
      "Desk Lamps",
      "Desk Accessories",
      "Task Chairs",
      "Ergonomic Chairs",
      "Filing Accessories",
      "Shelving Units",
      "Bulletin Boards",
    ],
  },
  {
    name: "Outdoor Furniture",
    subcategories: [
      "Patio Sets",
      "Outdoor Seating",
      "Outdoor Tables",
      "Outdoor Dining",
      "Outdoor Accessories",
      "Umbrellas & Canopies",
      "Outdoor Rugs",
      "Outdoor Lighting",
      "Fire Pits & Patio Heaters",
      "Outdoor Decor",
      "Planters & Garden Beds",
      "Grills & Outdoor Cooking",
    ],
  },
  {
    name: "Kids' Furniture",
    subcategories: [
      "Beds",
      "Dressers & Chests",
      "Nightstands",
      "Desks & Chairs",
      "Bookcases",
      "Toy Boxes & Storage",
      "Kids' Bedding",
      "Kids' Rugs",
      "Kids' Decor",
      "Play Tents & Tunnels",
      "Rocking Chairs",
      "Bean Bag Chairs",
    ],
  },
  {
    name: "Entryway Furniture",
    subcategories: [
      "Console Tables",
      "Entryway Benches",
      "Coat Racks & Hooks",
      "Shoe Storage",
      "Umbrella Stands",
      "Entryway Sets",
      "Mirrors",
      "Rugs",
      "Lighting",
      "Wall Art",
      "Decorative Baskets",
    ],
  },
  {
    name: "Home Bar Furniture",
    subcategories: [
      "Bar Cabinets",
      "Bar Carts & Serving Carts",
      "Wine Racks",
      "Bar Stools",
      "Bar Sets",
      "Glassware & Bar Tools",
      "Bar Decor",
      "Neon Signs",
    ],
  },
];
