import {
  Image1,
  Image2,
  Image3,
  Image4,
  Image5,
  Image6,
  Image7,
} from "../images/jpeg/imagesPng";

export const dummyProductsData = [
  {
    _id: "1",
    name: "luxury bedroom chair",
    image: Image1,
    images: [],
    price: 5544,
    rating: 5,
    priceSymbol: "$",
    status: "in stock",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.",
    reviews: [
      {
        rating: 2,
        text: "Lorem ipsum dolor sit amet, consectetur,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.",
        date: new Date(),
        name: "fortune",
      },
      {
        rating: 4,
        text: "Lorem ipsum dolor sit amet, consectetur,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.",
        date: new Date(),
        name: "fortune",
      },
      {
        rating: 3,
        text: "Lorem ipsum dolor sit amet, consectetur,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.",
        date: new Date(),
        name: "fortune",
      },
      {
        rating: 5,
        text: "Lorem ipsum dolor sit amet, consectetur,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.",
        date: new Date(),
        name: "fortune",
      },
      {
        rating: 1,
        text: "Lorem ipsum dolor sit amet, consectetur,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.",
        date: new Date(),
        name: "fortune",
      },
    ],
  },

  {
    _id: "2",
    name: "luxury bedroom chair",
    image: Image2,
    images: [],
    price: 5544,
    rating: 3,
    priceSymbol: "$",
    status: "out of stock",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.",
    reviews: [
      {
        rating: 2,
        text: "Lorem ipsum dolor sit amet, consectetur,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.",
        date: new Date(),
        name: "fortune",
      },
      {
        rating: 4,
        text: "Lorem ipsum dolor sit amet, consectetur,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.",
        date: new Date(),
        name: "fortune",
      },
      {
        rating: 3,
        text: "Lorem ipsum dolor sit amet, consectetur,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.",
        date: new Date(),
        name: "fortune",
      },
      {
        rating: 5,
        text: "Lorem ipsum dolor sit amet, consectetur,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.",
        date: new Date(),
        name: "fortune",
      },
      {
        rating: 1,
        text: "Lorem ipsum dolor sit amet, consectetur,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.",
        date: new Date(),
        name: "fortune",
      },
    ],
  },
  {
    _id: "3",
    name: "luxury bedroom chair",
    image: Image3,
    images: [],
    price: 5544,
    rating: 2,
    priceSymbol: "$",
    status: "being restocked",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.",
    reviews: [
      {
        rating: 2,
        text: "Lorem ipsum dolor sit amet, consectetur,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.",
        date: new Date(),
        name: "fortune",
      },
      {
        rating: 4,
        text: "Lorem ipsum dolor sit amet, consectetur,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.",
        date: new Date(),
        name: "fortune",
      },
      {
        rating: 3,
        text: "Lorem ipsum dolor sit amet, consectetur,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.",
        date: new Date(),
        name: "fortune",
      },
      {
        rating: 5,
        text: "Lorem ipsum dolor sit amet, consectetur,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.",
        date: new Date(),
        name: "fortune",
      },
      {
        rating: 1,
        text: "Lorem ipsum dolor sit amet, consectetur,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.",
        date: new Date(),
        name: "fortune",
      },
    ],
  },
  {
    _id: "4",
    name: "luxury bedroom chair",
    image: Image4,
    images: [],
    price: 5544,
    rating: 1,
    priceSymbol: "$",
    status: "in stock",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.",
    reviews: [
      {
        rating: 2,
        text: "Lorem ipsum dolor sit amet, consectetur,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.",
        date: new Date(),
        name: "fortune",
      },
      {
        rating: 4,
        text: "Lorem ipsum dolor sit amet, consectetur,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.",
        date: new Date(),
        name: "fortune",
      },
      {
        rating: 3,
        text: "Lorem ipsum dolor sit amet, consectetur,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.",
        date: new Date(),
        name: "fortune",
      },
      {
        rating: 5,
        text: "Lorem ipsum dolor sit amet, consectetur,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.",
        date: new Date(),
        name: "fortune",
      },
      {
        rating: 1,
        text: "Lorem ipsum dolor sit amet, consectetur,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.",
        date: new Date(),
        name: "fortune",
      },
    ],
  },
  {
    _id: "5",
    name: "luxury bedroom chair",
    image: Image5,
    images: [],
    price: 5544,
    rating: 5,
    priceSymbol: "$",
    status: "out of stock",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.",
    reviews: [
      {
        rating: 2,
        text: "Lorem ipsum dolor sit amet, consectetur,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.",
        date: new Date(),
        name: "fortune",
      },
      {
        rating: 4,
        text: "Lorem ipsum dolor sit amet, consectetur,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.",
        date: new Date(),
        name: "fortune",
      },
      {
        rating: 3,
        text: "Lorem ipsum dolor sit amet, consectetur,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.",
        date: new Date(),
        name: "fortune",
      },
      {
        rating: 5,
        text: "Lorem ipsum dolor sit amet, consectetur,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.",
        date: new Date(),
        name: "fortune",
      },
      {
        rating: 1,
        text: "Lorem ipsum dolor sit amet, consectetur,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.",
        date: new Date(),
        name: "fortune",
      },
    ],
  },
  {
    _id: "6",
    name: "luxury bedroom chair",
    image: Image6,
    images: [],
    price: 5544,
    rating: 4,
    priceSymbol: "$",
    status: "being restocked",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.",
    reviews: [
      {
        rating: 2,
        text: "Lorem ipsum dolor sit amet, consectetur,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.",
        date: new Date(),
        name: "fortune",
      },
      {
        rating: 4,
        text: "Lorem ipsum dolor sit amet, consectetur,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.",
        date: new Date(),
        name: "fortune",
      },
      {
        rating: 3,
        text: "Lorem ipsum dolor sit amet, consectetur,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.",
        date: new Date(),
        name: "fortune",
      },
      {
        rating: 5,
        text: "Lorem ipsum dolor sit amet, consectetur,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.",
        date: new Date(),
        name: "fortune",
      },
      {
        rating: 1,
        text: "Lorem ipsum dolor sit amet, consectetur,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.",
        date: new Date(),
        name: "fortune",
      },
    ],
  },
  {
    _id: "7",
    name: "luxury bedroom chair",
    image: Image7,
    images: [],
    price: 5544,
    rating: 3,
    priceSymbol: "$",
    status: "in stock",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.",
    reviews: [
      {
        rating: 2,
        text: "Lorem ipsum dolor sit amet, consectetur,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.",
        date: new Date(),
        name: "fortune",
      },
      {
        rating: 4,
        text: "Lorem ipsum dolor sit amet, consectetur,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.",
        date: new Date(),
        name: "fortune",
      },
      {
        rating: 3,
        text: "Lorem ipsum dolor sit amet, consectetur,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.",
        date: new Date(),
        name: "fortune",
      },
      {
        rating: 5,
        text: "Lorem ipsum dolor sit amet, consectetur,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.",
        date: new Date(),
        name: "fortune",
      },
      {
        rating: 1,
        text: "Lorem ipsum dolor sit amet, consectetur,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.,Lorem ipsum dolor sit amet, consectetur adipiscing elit. Magna in est adipiscing in phasellus non in justo.",
        date: new Date(),
        name: "fortune",
      },
    ],
  },
];
// "http://localhost:3000/_next/image?url=http%3A%2F%2F127.0.0.1%3A8887%2Fjpeg%2FchairLuxury.png&w=640&q=75",
// http://127.0.0.1:8887/jpeg/chairLuxury.png
